Layout/SpaceInsideParens:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLines:
  Enabled: false
